DROP DATABASE IF EXISTS tracker_db;
CREATE DATABASE tracker_db;

USE tracker_db;

CREATE TABLE departments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE roles (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) UNIQUE NOT NULL,
  salary DECIMAL UNSIGNED NOT NULL,
  departments_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (departments_id),
  REFERENCES departments(id),
  ON DELETE SET NULL
);

CREATE TABLE employees (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) UNIQUE NOT NULL,
  last_name VARCHAR(30) UNIQUE NOT NULL,
  role_id INT UNSIGNED NOT NULL,
  manager_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (role_id),
  REFERENCES departments(id),
  ON DELETE SET NULL
);